### ISSUE TITLE
Concurrency module accessing issue

### ISSUE THREAD

**Issue by dreampuf** [go-python/gpython#128]
In order to capture all `sys.stdout`, I set up a hook before code evaluation and figure out it has to have a lock to avoid the concurrency. I understand the modules play the same way as CPython does. But as a Golang library, I just wondering know if there is any better way to do so.

```golang
func (e *Engine) Eval(ctx context.Context, code *Code, locals py.StringDict) (py.Object, error) {
	e.lock.Lock()
	defer e.lock.Unlock()

        sys := py.MustGetModule("sys")
	buf := &Buffer{bytes.NewBuffer(nil)}
	original := sys.Globals["stdout"]
	sys.Globals["stdout"] = buf
	result, err := py.VmRun(e.globals, locals, code, nil)
	sys.Globals["stdout"] = original
	return result, err
}
```

**Comment by ncw** [comment]
gpython doesn't use any locking at the moment - it is expected to be running single threaded.

There isn't a lock you need to take **yet**!

**Comment by dreampuf** [comment]
Sorry about the partial code example. I have an outer scheduler to invoke this function. It might call multiple times at the same time. The `sys.stdout` might be overwrite if this is no lock.

**Comment by ncw** [comment]
I'll close this now then as I think your question is answered :-)
