### ISSUE TITLE
gPython's Killer app?

### ISSUE THREAD

**Issue by PythonLinks** [go-python/gpython#129]
A killer app is the app that makes the platform take off.  Spreadsheets were the original killer api for the apple2 and PCs.

So what is the killer app for gPython?    I have a  couple of ideas, but I am curious to see what everyone else has to say first. 

As part of this thread it would be interesting to discuss the strengths of gPython vs Rust Python and cPython.

I do know that cPython developers are working on multiple interpreters.  It keeps getting delayed.  But AFAIK, it will be one cPython interpreter per OS thread, whereas gPython potentially offers multiple cPython interpreters per OS thread.

So what do you think is the killer app for gPython?

**Comment by woodyZootopia** [comment]
I am wondering to create a language server for the development of Python, and gPython may be suited for it. The current langservers aren't really good (Palantir's pyls is really slow because it's just piling ready-made plugins and Microsoft's one is only for VSCode). Do you think we can create some fast and decent langserver with gPython?

**Comment by corona10** [comment]
Language server will be a great application of gPython

**Comment by PythonLinks** [comment]
For those who do not know what a language server is:
https://langserver.org/

So I guess every language server client would have their own instance of a python language server running in their own goRoutine.   That makes a lot of sense to me as something best done in gPython. 

In fact I need one of these.   The forest wiki includes a Python editor in the browser.  You can see a syntax checking demo here. 
https://demo.forestwiki.com/HtmlContentTypes/python.py/acedemo
Basically it works by compiling the code using Pyodide, and reporting the errors. 
So much better to have a language server.   
I took a look at the Palantir language server.  It requires PyFlakes.  PyFlakes includes some c code, so it will not run on Pyodide in the browser.  But if we did the languge server in GoLang, it compiles to webassembly, I could run it in the browser, and life would be great.  

The whole PythonBuddy community would be interested in this project, as well as many other 
projects.  And since it appeals to many Python developers, you should get a lot of support.   It sounds like a great project.  

My own pet peeve is that such huge amounts of money have been invested in Machine Learning.  Could we first please do the basic engineering that the world needs.  Such as a good language server with multiple simultaneous interpreters.

**Comment by corona10** [comment]
I think we can update the README file as the application section if someone uses gpython for their project.

I am really happy to accept the PR if someone submits the PR for this.
