### ISSUE TITLE
Cancelled: Online gPython Sprint Saturday March 21

### ISSUE THREAD

**Issue by PythonLinks** [go-python/gpython#130]
Nobody showed up, so this is cancelled.  

This Saturday I will be hosting an online gPython sprint, starting at 10 am Central European time, GMT +1.  If we can find North American volunteer organizers, it can go into the evening in North America. 

This sprint has 4 goals.  

1.  Improve gPython.  Fix and accept the pull requests, fix the issues, and improve performance.   I want to be able to use multiple Python Interpreters each running in their own goroutine. 

2. Provide an alternative to conference sprints.  Because of Coronavirus, the responsible thing is to postpone conferences, and practice social isolation.  But it is lonely, so this is also a social event.  I already feel less lonely. Sadly I cannot offer pizza, but we will  break for lunch and voice chat at 1 pm.  (Would any sponsor be willing to offer multiple pizza deliveries all around the world?)

3.  Learn some GoLang and Python.  When I look at the market, the developers I respect most, and the ones who are most valuable, are those who know both GoLang and Python, and know when to use which one.   We can all learn more of both languages.   What would you like to learn more about?

4. Onboard beginners.  The goal is to make a very welcoming environment for beginner sprinters.   Which issues should be reserved for beginners?  Who is willing to run those groups and mentor beginners?

There will be two broad categories of activities.  GoLang development, and Python development.  Within GoLang, the focus will be first on fixing and accepting pull requests, and then issues.  Within the Python category, the focus will be on porting libraries and applications to gPython.  

I am currently planning on running these sprints on a discord server.  You can sign up here.  https://discord.gg/rKq8x3 You will be able to see who else is participating.  @Corona10 will be joining us from Korea.  He is one of the gPython maintainers and has the authority to approve pull requests.  Initially there are just two chat rooms.  One chat room called planning-the-sprint and one for voting.  Eventually, each pull request, issue, or port will get their own chat room.  There will also be a welcome chat room and multiple lunch tables on different topics.  In the voting chat room, you can already propose and vote on lunch topics.   If we get enough signups,  I will ask one person to be moderate on each issue/topic, and a second to be a backup person.   Which issue interests you most?

Would anyone volunteer to run one of the pull request or issue sprints?  Or be a backup person? Would anyone want to be a backup person for me? A US person would be great, because then they can keep the sprint running when Europe and I go to sleep.

Comments and discussion are most appreciated. 
[Please retweet](https://twitter.com/PythonLinks/status/1239603072248225792).

**Comment by corona10** [comment]
@PythonLinks Great, Although I live in GMT+9, I will participate the sprint if possible.
Thanks for the information

**Comment by PythonLinks** [comment]
@Corona10 
When I organized this I was very mindful of the Asian countries.  But getting up too early will make me less effective.  If you are willing to be an organizer, we can start the sprint at 10 am Korean Time GMT +9, and then restart it at 10 am central European time GMT +1.  Hopefully we can find a North American  coordinator as well.  
If anyone  is considering attending, please say so, it encourages the others.  The best way is to join the discord server.  Then there is a count of people, and a way to contact you.    The more social way is to also post a message here saying that you plan on attending, and saying what issue motivates you most, and maybe volunteering to be an issue leader.  
Once we have a few issue leaders, I will announce it on reddit, and a lot more people will sign up.  I will be advertising this to both the Python and GoLang communities. 
I also think we should have two groups for beginners.  One for beginners in GoLang, one for beginners in Python.

**Comment by corona10** [comment]
@PythonLinks
 
Sprint event time will be not an issue for me :)
In personal, I 'd like to participate in the sprint with other countries' people.
It will be a great experience if I can participate in this sprint!
https://www.timeanddate.com/worldclock/converter.html?iso=20200321T090000&p1=235&p2=tz_cet

**Comment by PythonLinks** [comment]
Nobody, showed up, so I cancelled this event.  Quite the pity.  Please feel free to delete this issue tomorrow,  but maybe leave it up for today, if anyone shows up.

**Comment by sbinet** [comment]
sad, but not unexpected, considering the current situation worldwide.

don't let this unfortunate event discourage you though!
