### ISSUE TITLE
Readme upgrade

### ISSUE THREAD

**Issue by PythonLinks** [go-python/gpython#131]
I am about to announce the sprint on Python and GoLang reddits.  We will have a bunch of people coming to take a look, so I would like the readme to be as good as possible before then.  It is already quite good.  Covers all of the important information.  The only thing it lacks is motivation and comparison to other python interpreters.  So here is my attempt at an additional paragraph or two for the readme file. 
# Motivation
The  advantage of  gPython over cPython  is that it will allow [multiple  Python interpreters](https://www.python.org/dev/peps/pep-0554/) to be running in the in the same process at the same time. 

Python 3.8 does have multiple interpreters, but their Python api was not included in the [Python 3.8 release](https://docs.python.org/3/whatsnew/3.8.html).  It keeps getting postponed. 

Worse yet each cPython interpreter will be an OS thread.  In contrast each gPython interpreter is a goroutine, which is a light weight thread.  GoLang handles their scheduling. 

Another motivation is that  gPython has excellent access to GoLang libraries.  For example I recently replaced my  NGINX server with the brilliant [Caddy web server](https://caddyserver.com/).  With gPython, I could have my caddy server, and all of my Python servers in a single process. No context switching required.  
________________
So what do you think about this addition to the ReadMe file?

**Comment by corona10** [comment]
This feature is not implemented yet,
If we implement the feature, IMHO we can update the README on that time :)

Thanks for the suggestion.
