### ISSUE TITLE
Is it safe to use gpython interpreter in concurrent processing?

### ISSUE THREAD

**Issue by fuz-woo** [go-python/gpython#132]
I've noted that gpython is not support concurrent processing library yet. Is it safe if I use gpython in multi thread then? If not, how should I make it synchronized.

**Comment by ncw** [comment]
Gpython has no way of making threads (or go routines) yet.

So I guess you are asking about making multiple instances of gpython? I think this should be fine but there may be some global state I'm forgetting about.

In due course I'd like to add a create a go-routine function to gpython. From that point normal go style locking will need to be used to access dictionaries concurrently etc.

**Comment by drew-512** [comment]
Multi interpreter instances ("contexts") are supported with [PR144](https://github.com/go-python/gpython/pull/144).  This opens the door to many possibilities.

**Comment by drew-512** [comment]
@sbinet I move to close this as resolved with v0.1.0 (`py.Context`) now live.

**Comment by sbinet** [comment]
fixed w/ #158
