### ISSUE TITLE
Embed into another program

### ISSUE THREAD

**Issue by alexec** [go-python/gpython#138]
Is it possible to embed this? Like Otto (https://github.com/robertkrimen/otto).

**Comment by sbinet** [comment]
as can be seen in https://github.com/go-python/gpython/blob/master/main.go#L120, embedding a gpython vm is like:

```go
res, err := vm.Run(module.Globals, module.Globals, code, nil)
```

ie:
- https://pkg.go.dev/github.com/go-python/gpython/vm#Run

is that too low level an API?

**Comment by alexec** [comment]
I actually figured it out:

https://github.com/argoproj/argo-workflows/blob/master/util/python/python.go

I wrote code to convert Go types into Python types. Is there another way?

**Comment by miathedev** [comment]
My question is similar. I would like to execute methods of a Python script from my Golang application. 
Is that possible in a easy way? I need something more high-level fashioned.

**Comment by drew-512** [comment]
In the coming days I'll PR the main README and add updated docs and snippets for newcomers to more easily get up and running.

**Comment by sbinet** [comment]
fixed w/ https://github.com/go-python/gpython/pull/159
