### ISSUE TITLE
'str' has no attribute 'find'" (and similar errors)

### ISSUE THREAD

**Issue by alexec** [go-python/gpython#139]
I'm importing the builtin package, but I often get errors like this. 

What have I done wrong please?

**Comment by sbinet** [comment]
AFAICT, you've done nothing wrong.
having full Python compliance (even on builtin types), is still a WIP.

**Comment by sbinet** [comment]
I've collect #188 that added `str.find`.
what are the other methods you'd need?

**Comment by dankox** [comment]
I know this is older issue and should be probably closed, but as it's still open, I would just drop by and say that `join` would be nice to have. I can open a new issue if necessary.

**Comment by sbinet** [comment]
yes, please open another issue.
