### ISSUE TITLE
all([]) should return false

### ISSUE THREAD

**Issue by raff** [go-python/gpython#14]
From python documentation at https://docs.python.org/3/library/functions.html#all
   Return True if all elements of the iterable are true (or if the iterable is empty).

**Comment by corona10** [comment]
@raff 

Hi, raff on my gpython it works well.

```
➜  ~ gpython
>>> a = []
>>> all(a)
False
>>> all([])
False
>>>
```

Is there any other issue which you intended?

**Comment by raff** [comment]
Sorry, I meant it should return True, according to python specs. See the link and the python implementations in there.
