### ISSUE TITLE
Broken, SIGSEGV

### ISSUE THREAD

**Issue by williammortl** [go-python/gpython#161]
The current repo is broken...

after "go build"

```
wmortl@Discovery:/mnt/e/Code/gpython$ ./gpython
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5986b1]

goroutine 1 [running]:
main.main()
        /mnt/e/Code/gpython/main.go:49 +0x171
```

Seems to be context related from line 49

**Comment by sbinet** [comment]
thanls for the report.
this should be fixed w/ #162.

we ought to do a better job at testing the `gpython` binary...

**Comment by williammortl** [comment]
@sbinet no worries! I'm going to be around here a lot, as I am packaging gpython into a plugin as part of a new type of compute cluster that I am creating for my PhD dissertation!

**Comment by sbinet** [comment]
sounds fun :)
(and welcome)
