### ISSUE TITLE
How would i go about writing a new module?

### ISSUE THREAD

**Issue by glaukiol1** [go-python/gpython#168]
Hi

I want to contribute to this project by writing a module; specifically the JSON module (the one that is in python's standard library). I have seen the source code and have an idea of how I should go about this. So my question is; do I create a folder and put the .go file in there? Something like `json/json.go`? Also any tips on writing modules would help, thanks!

**Comment by drew-512** [comment]
Hi friend, have you looked at the 'Vacation' embedded module example?  That should demonstrate all the things you're looking for.  Feel free to ask specific questions here.    

Drew

**Comment by raff** [comment]
The math package also implements Python "math". Look for the init method at the bottom, where it registers the module: https://github.com/go-python/gpython/blob/master/math/math.go#L1290

**Comment by glaukiol1** [comment]
Im stuck on converting a Go map[string]interface{} to a py.StringDict. Any help?

**Comment by glaukiol1** [comment]
@raff @drew-512

**Comment by ahdekkers** [comment]
Was any progress made with this?

**Comment by drew-512** [comment]
I'm happy to work with anyone is seriously interested in building.  Happy to give a tour and walk through of the codebase.  That said, the [embedding example](https://github.com/go-python/gpython/tree/main/examples/embedding) is relatively easy to grok.  Anyone who reads the comments and follows the breadcrumbs will be ready to write a module.
