### ISSUE TITLE
meta: cross-check with CPython

### ISSUE THREAD

**Issue by sbinet** [go-python/gpython#19]
as shown in #14, we should cross-check that our tests agree with some reference CPython version (presumably, CPython-3.)

so we should probably put some wiring so that each `test.py` script is run with both `gpython` and `cpython`.

**Comment by ncw** [comment]
That is what the [py3test.py]https://github.com/go-python/gpython/blob/master/py3test.py) binary does.

It currently requires python 3.4 though maybe that should be relaxed to python3?

We should probably fix it and plumb it into the CI!

**Comment by sbinet** [comment]
ah! :)

yes, we should probably do that.

**Comment by ncw** [comment]
I've implemented this in eaa7d286460777b536b404e09a1bd352f2012a78 (oops forgot the link to the issue).
