### ISSUE TITLE
Decimal.from_float takes bad arguments crashing gpython

### ISSUE THREAD

**Issue by xiaxinmeng** [go-python/gpython#199]
In the following example, Decimal.from_float take bad arguments and trigger segfault of gpython

Crashing message: segmentation fault

```
from decimal import Decimal

class BadFloat(float):

    def as_integer_ratio(self):
        return 1

    def __abs__(self):
        return self
Decimal.from_float(BadFloat(1.2))
```
environment: gpython 0.1.0 on Ubuntu 18.04, and gpython main(https://github.com/go-python/gpython/commit/6f8e06a4660709ab44398d8b1a18738aa407b1c3 on Oct 5)

**Comment by ncw** [comment]
gpython doesn't come with the `Decimal` module - where did you get these from?

Please give steps to reproduce with `gpython`

Thanks
