### ISSUE TITLE
Errors are suppressed in generator comprehensions

### ISSUE THREAD

**Issue by ncw** [go-python/gpython#32]
```
>>> list(i for x in range(10))
[]
```

Which should have output

```
>>> list(i for x in range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <genexpr>
NameError: name 'i' is not defined
```

**Comment by corona10** [comment]
@ncw I will take a look this issue

**Comment by ncw** [comment]
@corona10 are you getting anywhere with this? Do you need help?

**Comment by corona10** [comment]
@ncw 
https://github.com/go-python/gpython/blob/2609237ddef238242467618344ca5fb6775302e8/py/generator.go#L100
Well, I tracked the code and I found that something issue in this side. 
But I don't know which is the main reason for this issue yet.

So if you already solve this issue, Then please upload a PR for this issue :)
I can learn something from your PR.

**Comment by ncw** [comment]
> Well, I tracked the code and I found that something issue in this side.
> But I don't know which is the main reason for this issue yet.

I haven't figured it out either!

But yes, it is probably something to do with making a new Vm Frame and the errors being suppressed there rather than propagated.

**Comment by corona10** [comment]
@ncw 
I found the main reason for this bug.
I will upload the PR soon

**Comment by ncw** [comment]
> I found the main reason for this bug.
> I will upload the PR soon

Great.  Don't forget a failing test case :-)
