### ISSUE TITLE
range: 'range' object is not subscriptable

### ISSUE THREAD

**Issue by corona10** [go-python/gpython#46]
Range object should support get_item operation :)

## gpython

``` python
>>> a = range(10)
>>> a[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
TypeError: "'range' object is not subscriptable"
```

## python3
``` python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = range(10)
>>> a[0]
0
```

**Comment by ncw** [comment]
I can't imagine why you'd want to do that, but yes it looks like a bug :-)

**Comment by corona10** [comment]
@ncw 
Oh, I am finding out feature with not compatible with cpython3.
so sometimes I write something strange code.
And this bug was found from practical code and this code is just an essential part of that bug to reproduce.

**Comment by ncw** [comment]
> @ncw
> Oh, I am finding out feature with not compatible with cpython3.
> so sometimes I write something strange code.
> And this bug was found from practical code and this code is just an essential part of the bug to reproduce.

I see!

In idea: at some point we could use [go-fuzz](https://github.com/dvyukov/go-fuzz) to find code which doesn't behave the same way in gpython and python3.

**Comment by corona10** [comment]
@ncw Yeah it would be a good choice!
