### ISSUE TITLE
no such file or directory at first time gpython repl

### ISSUE THREAD

**Issue by msAlcantara** [go-python/gpython#62]
I installed gpython with the command `go get github.com/go-python/gpython` and when I run in the first time in repl I get the next message error:
`Failed to open history: open /home/matheus/.gpyhistory: no such file or directory`
the repl do not stop working, and not presented no problem at first, but should be nice dont show this kind of error since that this does not hassles the gpython experience repl

**Comment by ncw** [comment]
I think this would be quite easy to fix - fancy having a go?

**Comment by msAlcantara** [comment]
Yeah, I can do this
