### ISSUE TITLE
SyntaxError of global declaration don't stop program

### ISSUE THREAD

**Issue by HyeockJinKim** [go-python/gpython#72]
```python
a = 3
global a
print(a)

b = 2 + 5
print(b)
```
This code generate syntax error, but gpython doesn't stop program

### Expected Result
```bash
Hyeockz:bin hyeockjinkim$ python3 g.py 
  File "g.py", line 2
    global a
SyntaxError: name 'a' is assigned to before global declaration
```

### Actual Result
```bash
2019/09/09 00:08:36 name 'a' is assigned to before global declaration
3
7
```
SyntaxError in python3 is Error, not warning. So I think it should be modified.

**Comment by HyeockJinKim** [comment]
If this issue is valid, can I take it?

**Comment by ncw** [comment]
Interesting, that behaviour has changed from python3.4 to python3.7

Gpython is following python3.4 for the moment so it should be generating a SyntaxWarning

```
$ /opt/python3.4/bin/python3.4 /tmp/z.py 
/tmp/z.py:2: SyntaxWarning: name 'a' is assigned to before global declaration
  global a
3
7
```

```
$ python3.7 /tmp/z.py 
  File "/tmp/z.py", line 2
    global a
    ^
SyntaxError: name 'a' is assigned to before global declaration
```



> If this issue is valid, can I take it?

Happy to have help, so yes!

**Comment by corona10** [comment]
@ncw  
FYI, 
@HyeockJinKim is a mentee of OSS program name `Contributhon` of Korea government.
It's a similar program GSoC. 
I am mentoring @HyeockJinKim for a month.

There are also some people(4-5) who have contributed for the first time gpython project.
so they need our help too.

And I am going to assign an issue to them with `Contributhon 2019`tag. (It is the program name)

**Comment by corona10** [comment]
@ncw  
FYI,  @HyeockJinKim is a mentee of OSS program name `Contributhon` of Korea government.
It's a similar program like GSoC. 
(A few months ago I posted a mailing list about [this prgram](https://groups.google.com/forum/#!topic/go-python/i7C-1nDiwdU) )
I am mentoring @HyeockJinKim for a month.

There are also some people(4-5) who want to contribute gpython project for the first time.
so they need our help too.

And I am going to assign issues to them with `Contributhon 2019`tag. (It is the program name)

**Comment by corona10** [comment]
cc @sbinet

**Comment by ncw** [comment]
Fantastic new @corona10 - what a great project! Ping me on an issue if you need help :-)

**Comment by sbinet** [comment]
and welcome in the wonderful world of mentoring :)
