### ISSUE TITLE
How does format string work with `$`?

### ISSUE THREAD

**Issue by tim-st** [go-python/gpython#75]
I'm [currently implementing](https://github.com/tim-st/gpython/commit/ffb374f6ae4c3e291f1fdefc235bc03f34727bbc) `sorted`, the signature is:
```
sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.
```

It already works as expected when passing either exactly one argument or all three.
When I only pass the first and the third, the third is interpreted as the second.
```python
Python 3.4.0 (none, unknown)
[Gpython dev]
- os/arch: windows/amd64
- go version: go1.13
>>> l = [1.1, 1, 3]
>>> sorted(l)
[1, 1.1, 3]
>>> sorted(l, reverse=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    FIXME line of source goes here
TypeError: "'bool' object is not callable"
>>> sorted(l, key=None, reverse=False)
[1, 1.1, 3]
>>> sorted(l, key=None, reverse=True)
[3, 1.1, 1]
>>>
```

I think my format string for `py.ParseTupleAndKeywords` should be `"O|$Op:sorted"`, but this doesn't work too. Currently I have the following code:

```go
func builtin_sorted(self py.Object, args py.Tuple, kwargs py.StringDict) (py.Object, error) {
	var iterable py.Object
	var keyFunc py.Object = py.None
	var reverse py.Object = py.False
	err := py.ParseTupleAndKeywords(args, kwargs, "O|Op:sorted", []string{"iterable", "key", "reverse"}, &iterable, &keyFunc, &reverse)
	if err != nil {
		return nil, err
	}
	l, err := py.SequenceList(iterable) // make a copy of the list
	if err != nil {
		return nil, err
	}
	err = SortInplace(l, keyFunc, reverse) // sort the copy in place
	if err != nil {
		return nil, err
	}
	return l, nil
}
```

Additionally Python doesn't allow `sorted(list(), None, False)`, GPython allows this using the code above.

**Comment by tim-st** [comment]
Seems that also CPython's `PyArg_ParseTupleAndKeywords` doesn't support "keyword arguments only" even when `$` is set, it's still callable as optional argument, so I have to implement it using manual checking of all args.

The other thing mentioned could be a bug, but I test this again, once the implementation is finished.

**Comment by tim-st** [comment]
Update: I got it working similar like implemented in `min_max` function. It seems the only way here is to process the `args` and `kwargs` using two different ways.
First
```go
	var iterable py.Object
	err := py.UnpackTuple(args, nil, funcName, 1, 1, &iterable)
	if err != nil {
		return nil, err
	}
```
and then the `kwargs`:
```go
	var keyFunc py.Object
	var reverse py.Object
	err = py.ParseTupleAndKeywords(nil, kwargs, "|$OO:"+funcName, []string{"key", "reverse"}, &keyFunc, &reverse)
	if keyFunc == nil {
		keyFunc = py.None
	}
	if reverse == nil {
		reverse = py.False
	}
	if err != nil {
		return nil, err
	}
```
Using this way it's possible two allow the same calling ways like CPython does.
When using the code above also the call order of kwargs is not a problem anymore.

**Comment by ncw** [comment]
> Seems that also CPython's `PyArg_ParseTupleAndKeywords` doesn't support "keyword arguments only" even when `$` is set, it's still callable as optional argument, so I have to implement it using manual checking of all args.

The implementation of `PyArg_ParseTupleAndKeywords` probably isn't 100% compatible with CPythons.. It tends to evolve when needed to make the next thing work!

**Comment by tim-st** [comment]
Ok, it seems there are some problems with format strings like ""|$Op:funcName". When using optional kwargs only `O` seems to work, others panic on nil error.

**Comment by ncw** [comment]
> Ok, it seems there are some problems with format strings like `"|$Op:funcName"`. When using optional kwargs only `O` seems to work, others panic on nil error.

Might need fixing up... Would welcome a PR :-)
