### ISSUE TITLE
Implement set repr

### ISSUE THREAD

**Issue by corona10** [go-python/gpython#85]
## Expected

````python

>>> a = {1, 2, 3}
>>> a
{1, 2, 3}
````

## Actual
````python
>>> a = {1, 2, 3}
>>> a
<set instance at 0xc0000aa018>
````

**Comment by xarus01** [comment]
Hi, mind if I try on this issue?

**Comment by corona10** [comment]
@xarus01 Please go ahead

**Comment by SanggiHong** [comment]
@xarus01 @corona10 May I take this issue?
I'd like to implement operations of the set, so it would be very helpful if this is implemented before the work.
