### ISSUE TITLE
print function's "end" option error in CPython

### ISSUE THREAD

**Issue by Sungmin-Joo** [go-python/gpython#93]
The following code writes different string to the stream than in CPython:
```
print(1,2,3, end="||\n")
```

**Comment by ncw** [comment]
I think this is related to the argument parsing being wrong as identifed in #91

**Comment by drew-512** [comment]
fixed w/ https://github.com/go-python/gpython/pull/151

**Comment by sbinet** [comment]
fixed w/ #151.
